In [ ]:
import pandas as pd
import sqlite3 as sql

In [ ]:
conn=sql.connect('/sql-murder-mystery.db')

In [ ]:
print(conn)

<sqlite3.Connection object at 0x7cb37c8a1640>

In [ ]:
query_1='''
SELECT *
FROM crime_scene_report
WHERE city="SQL City"
ORDER BY date;
'''
pd.read_sql_query(query_1,conn)

,date,type,description,city
0,20170712,theft,"A lone hunter stalks the night, firing arrows ...",SQL City
1,20170820,arson,"Wield the Hammer of Sol with honor, Titan, it ...",SQL City
2,20171110,robbery,The Gjallarhorn shoulder-mounted rocket system...,SQL City
3,20180103,bribery,"Apparently, Cayde thought it necessary to expo...",SQL City
4,20180115,assault,"Hamilton: Lee, do you yield? Burr: You shot hi...",SQL City
5,20180115,assault,Report Not Found,SQL City
6,20180115,murder,Security footage shows that there were 2 witne...,SQL City
7,20180215,murder,REDACTED REDACTED REDACTED,SQL City
8,20180215,murder,Someone killed the guard! He took an arrow to ...,SQL City

In [ ]:
query_2='''
SELECT *
FROM crime_scene_report
WHERE date=20180115
AND type="murder";
'''
pd.read_sql_query(query_2,conn)

,date,type,description,city
0,20180115,murder,Life? Dont talk to me about life.,Albany
1,20180115,murder,"Mama, I killed a man, put a gun against his he...",Reno
2,20180115,murder,Security footage shows that there were 2 witne...,SQL City

In [ ]:
query_3='''
SELECT *
FROM person
WHERE address_street_name
LIKE "Franklin Ave";
'''
pd.read_sql_query(query_3,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,12207,Wilmer Wolever,509484,139,Franklin Ave,636825374
1,16371,Annabel Miller,490173,103,Franklin Ave,318771143
2,17683,Johnnie Schee,968887,1277,Franklin Ave,815977821
3,18651,Carleen Etoll,356746,22,Franklin Ave,193369255
4,22636,Zachary Ybarbo,768359,785,Franklin Ave,285346605
5,24737,Gema Nantz,273410,3968,Franklin Ave,180545802
6,30654,Clarita Rickels,418084,2254,Franklin Ave,714941023
7,32264,Shelby Dezeeuw,735415,1391,Franklin Ave,143197463
8,33793,Amado Mattan,161915,99,Franklin Ave,125205748
9,34592,Cordell Lindamood,592762,3657,Franklin Ave,509890333
10,36328,Domenic Laun,971080,3809,Franklin Ave,825329637
11,36400,Noe Pancoast,895755,3443,Franklin Ave,732212073
12,37616,Katelyn Schwerin,430143,332,Franklin Ave,392365033
13,46827,Bev Billiter,643591,2316,Franklin Ave,940192302
14,52059,Jordan Pelton,686854,2786,Franklin Ave,676224073
15,52075,Ezra Phy,928109,384,Franklin Ave,176404498
16,52121,Yelena Whitler,427830,3185,Franklin Ave,115106155
17,54817,Guy Bustard,213929,591,Franklin Ave,820850670
18,54896,Patty Wamsley,688488,1097,Franklin Ave,725272037
19,56142,William Shiver,741336,1926,Franklin Ave,219913461
20,57051,Lavette Koehl,137365,2284,Franklin Ave,776046786
21,59746,Ronny Gumbert,469722,3197,Franklin Ave,561067477
22,60944,Ricki Bidding,443364,2072,Franklin Ave,614976330
23,61001,Laurine Bousman,197150,247,Franklin Ave,431360364
24,61437,Colette Hollomon,661377,453,Franklin Ave,314956038
25,62292,Isaiah Holsten,913856,747,Franklin Ave,995368430
26,62520,Mariah Lepetich,450447,3086,Franklin Ave,797745632
27,67292,Renita Roperto,801041,625,Franklin Ave,894442480
28,69719,Hope Arzabala,311724,841,Franklin Ave,270289620
29,70050,Whitney Herkenratt,138462,3445,Franklin Ave,552518972
30,75510,Sebastian Ramnarase,333188,1127,Franklin Ave,315716580
31,76128,Ressie Razze,633497,1199,Franklin Ave,456366143
32,78170,Graig Summy,192325,3387,Franklin Ave,277793306
33,78408,Dante Eschen,218173,3447,Franklin Ave,135374633
34,78658,Blake Chrones,310242,2014,Franklin Ave,423048084
35,78830,Candice Train,814779,3255,Franklin Ave,717570815
36,83003,Wilmer Casella,672050,3564,Franklin Ave,569057540
37,83754,Maria Walsh,201334,2716,Franklin Ave,121282864
38,84531,Edgar Mendieta,315790,3881,Franklin Ave,458847132
39,87521,Moses Ikerd,638991,2283,Franklin Ave,797715435
40,88966,Raul Eads,570927,2066,Franklin Ave,764132739
41,93947,Omer Andreoni,605718,13,Franklin Ave,322594288
42,95119,Hong Lisa,825828,375,Franklin Ave,113438176
43,97913,Cameron Dilick,971988,2954,Franklin Ave,665147939
44,98744,Jordan Myntti,256116,3104,Franklin Ave,876030104

In [ ]:
query_4='''
SELECT *
FROM person
WHERE address_street_name
LIKE "Northwestern%"
ORDER BY address_number DESC
'''
pd.read_sql_query(query_4,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,14887,Morty Schapiro,118009,4919,Northwestern Dr,111564949
1,17729,Lasonya Wildey,439686,3824,Northwestern Dr,917817122
2,53890,Sophie Tiberio,957671,3755,Northwestern Dr,442830147
3,73368,Torie Thalmann,773862,3697,Northwestern Dr,341559436
4,96595,Coretta Cubie,303645,3631,Northwestern Dr,378403829
5,19420,Cody Schiel,890431,3524,Northwestern Dr,947110049
6,93509,Emmitt Aceuedo,916706,3491,Northwestern Dr,979073160
7,87456,Leonora Wolfsberger,215868,3483,Northwestern Dr,565203106
8,36378,Freddie Ellzey,267882,3449,Northwestern Dr,474117596
9,53076,Boris Bijou,664914,3327,Northwestern Dr,401191868
10,28360,Rashad Cascone,924517,3212,Northwestern Dr,838907424
11,23044,Val Portlock,924989,3143,Northwestern Dr,100593316
12,51114,Christena Saffell,814284,3055,Northwestern Dr,247657547
13,68690,Yer Modest,852404,3046,Northwestern Dr,419238039
14,44004,Alison Eska,327797,2951,Northwestern Dr,306417867
15,98593,Jonah Toner,578982,2947,Northwestern Dr,745853548
16,59307,Cyril Yongue,753524,2903,Northwestern Dr,866057839
17,34155,Allyson Lazenson,814209,2840,Northwestern Dr,991150469
18,90397,Dionna Kranwinkle,797260,2678,Northwestern Dr,278964807
19,54564,Sammie Sengun,217286,2590,Northwestern Dr,848854310
20,53699,Christian Pagano,628433,2585,Northwestern Dr,644772304
21,34352,Vincenza Burkhardt,436470,2512,Northwestern Dr,197913046
22,80921,Donovan Yackley,222395,2386,Northwestern Dr,515049359
23,96178,Galina Khuu,450248,2183,Northwestern Dr,398518185
24,81885,Kurtis Masuda,934201,2108,Northwestern Dr,201272595
25,88423,Teri Ehrich,510876,1879,Northwestern Dr,248637345
26,51552,Bonita Knie,764124,1726,Northwestern Dr,597137908
27,72076,Courtney Bordeaux,324614,1707,Northwestern Dr,347966356
28,81052,Calvin Czelusniak,471483,1516,Northwestern Dr,657531837
29,71924,Laurie Scronce,774116,1418,Northwestern Dr,254883636
30,23960,Kristopher Lagerberg,658777,1392,Northwestern Dr,492912529
31,70485,Andera Kostelecky,354822,1252,Northwestern Dr,787423012
32,22239,Dusty Sigafus,710517,1125,Northwestern Dr,724386723
33,18376,Josh Shi,653712,1091,Northwestern Dr,193899001
34,29608,Willetta Lurvey,800568,1028,Northwestern Dr,843751378
35,33415,Homer Simpson,108392,981,Northwestern Dr,871392019
36,55130,Shiloh Huntoon,472118,951,Northwestern Dr,826647644
37,44542,Ivory Mcgrevey,873842,897,Northwestern Dr,988557407
38,99826,Ivy Kazarian,994470,892,Northwestern Dr,208359813
39,25615,Olevia Morena,388477,812,Northwestern Dr,962831331
40,40760,Renata Faver,976650,745,Northwestern Dr,547572040
41,10010,Muoi Cary,385336,741,Northwestern Dr,828638512
42,39688,Abe Roeker,537445,689,Northwestern Dr,438969447
43,26758,Angelena Billman,942074,629,Northwestern Dr,341854756
44,75484,Del Tacderen,447887,607,Northwestern Dr,243821337
45,12711,Norman Apolito,667757,599,Northwestern Dr,778264744
46,85280,Donn Duin,569122,540,Northwestern Dr,613873810
47,40336,Fredia Billeter,251082,404,Northwestern Dr,108056488
48,15171,Weldon Penso,336999,311,Northwestern Dr,131379495
49,89906,Kinsey Erickson,510019,309,Northwestern Dr,635287661

In [ ]:
query_5='''
SELECT *
FROM interview
WHERE person_id=16371
'''
pd.read_sql_query(query_5,conn)

   person_id                                         transcript
0      16371  I saw the murder happen, and I recognized the ...

In [ ]:
query_6='''
SELECT *
FROM interview
WHERE person_id=14887
'''
pd.read_sql_query(query_6,conn)

   person_id                                         transcript
0      14887  I heard a gunshot and then saw a man run out. ...

In [ ]:
query_7='''
SELECT *
FROM get_fit_now_check_in
JOIN get_fit_now_member
ON get_fit_now_check_in.membership_id=get_fit_now_member.id
WHERE membership_id
LIKE "48Z%"
AND check_in_date=20180109
'''
pd.read_sql_query(query_7,conn)

,membership_id,check_in_date,check_in_time,check_out_time,id,person_id,name,membership_start_date,membership_status
0,48Z7A,20180109,1600,1730,48Z7A,28819,Joe Germuska,20160305,gold
1,48Z55,20180109,1530,1700,48Z55,67318,Jeremy Bowers,20160101,gold

In [ ]:
query_8='''
SELECT *
FROM drivers_license
WHERE plate_number
LIKE "%H42W%"
'''
pd.read_sql_query(query_8,conn)

,id,age,height,eye_color,hair_color,gender,plate_number,car_make,car_model
0,183779,21,65,blue,blonde,female,H42W0X,Toyota,Prius
1,423327,30,70,brown,brown,male,0H42W2,Chevrolet,Spark LS
2,664760,21,71,black,black,male,4H42WR,Nissan,Altima

In [ ]:
query_9='''
SELECT *
FROM person
WHERE license_id
LIKE "423327"
'''
pd.read_sql_query(query_9,conn)

,id,name,license_id,address_number,address_street_name,ssn
0,67318,Jeremy Bowers,423327,530,"Washington Pl, Apt 3A",871539279

THERFORE, THE MURDERER IS JEREMY BOWERS ......